# Generated by Django 6.1.1 on 2026-09-30 17:56

import django.db.models.deletion
import ledger.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('bank', 'bank'), ('card', 'card'), ('cash', 'cash'), ('wallet', 'wallet')], default='bank', max_length=10)),
                ('last4', models.CharField(blank=True, db_index=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=ledger.models.new_token, max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('essential', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=50)),
                ('sender_regex', models.CharField(blank=True, max_length=200)),
                ('body_regex', models.TextField()),
                ('kind', models.CharField(blank=True, help_text='Leave blank to infer from debit/credit words', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kind', models.CharField(choices=[('expense', 'expense'), ('income', 'income'), ('transfer', 'transfer'), ('lend', 'lend'), ('borrow', 'borrow'), ('repay_in', 'repay in'), ('repay_out', 'repay out')], default='expense', max_length=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('merchant', models.CharField(blank=True, max_length=200)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('raw_text', models.TextField(blank=True)),
                ('ref', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('ignored', 'ignored')], default='confirmed', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='amount_non_negative')],
            },
        ),
    ]
