# Generated by Django 6.1.1 on 2026-09-30 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name_plural': 'people & companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='kind',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('lend', 'Lent (they owe me)'), ('borrow', 'Borrowed (I owe them)'), ('repay_in', 'Repaid to me'), ('repay_out', 'Repaid by me')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ledger.party'),
        ),
    ]
