# Generated by Django 6.1.1 on 2026-09-30 18:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def rename_kinds(apps, schema_editor):
    Account = apps.get_model("ledger", "Account")
    Account.objects.filter(kind="bank").update(kind="savings")
    Account.objects.filter(kind="card").update(kind="credit_card")


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_parties'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_enabled', models.BooleanField(default=False, verbose_name="Daily “log today's spending” reminder")),
                ('daily_time', models.TimeField(default='21:00')),
                ('reminders_enabled', models.BooleanField(default=True, verbose_name='Bill, subscription and card statement reminders')),
                ('reminder_time', models.TimeField(default='09:00')),
            ],
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, unique=True)),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=100)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='account',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='account',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Pre-selected for new transactions'),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='account',
            name='statement_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, help_text='Transfers only, e.g. paying a card from savings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='kind',
            field=models.CharField(choices=[('savings', 'Savings account'), ('current', 'Current account'), ('credit_card', 'Credit card'), ('credit_line', 'Credit line'), ('loan', 'Loan'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='savings', max_length=12),
        ),
        migrations.CreateModel(
            name='Recurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('kind', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('transfer', 'Transfer'), ('lend', 'Lent (they owe me)'), ('borrow', 'Borrowed (I owe them)'), ('repay_in', 'Repaid to me'), ('repay_out', 'Repaid by me')], default='expense', max_length=10)),
                ('every', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('day', 'day(s)'), ('week', 'week(s)'), ('month', 'month(s)'), ('year', 'year(s)')], default='month', max_length=5)),
                ('next_due', models.DateField()),
                ('anchor_day', models.PositiveSmallIntegerField(editable=False, null=True)),
                ('remind_days_before', models.PositiveSmallIntegerField(default=0)),
                ('essential', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.category')),
            ],
            options={
                'ordering': ['next_due', 'name'],
            },
        ),
        migrations.RunPython(rename_kinds, migrations.RunPython.noop),
    ]
