# Generated by Django 6.1.1 on 2026-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_accounts_recurring_notify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-time', '-id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
