# Generated by Django 6.1.1 on 2026-09-30 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifysettings',
            name='daily_time',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='notifysettings',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
