# Generated by Django 6.1.1 on 2026-10-01 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_more_sms_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly limit', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.category')),
            ],
            options={
                'ordering': ['pattern'],
            },
        ),
    ]
