# Generated by Django 6.1.1 on 2026-10-02 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_more_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='interest_every',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Monthly'), (3, 'Quarterly'), (6, 'Half-yearly'), (12, 'Yearly')], default=3),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_next',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='notifysettings',
            name='interest_auto_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
