# Generated by Django 6.1.1 on 2026-10-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0012_cash_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interest_every',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Daily'), (1, 'Monthly'), (3, 'Quarterly'), (6, 'Half-yearly'), (12, 'Yearly')], default=3),
        ),
    ]
