# Generated by Django 6.1.1 on 2026-10-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0014_sms_templates_hdfc_card_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='split_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='split_shares', to='ledger.transaction'),
        ),
    ]
